### ISSUE TITLE
Build folder missing

### ISSUE THREAD

**Issue by Lilalou88** [timkurvers/valheim-macos#102]
Hello there, I did everything but don't have a build folder. The valheim.app icon is in the skeleton folder but not working. Any ideas?

**Comment by timkurvers** [comment]
Could you copy-paste the output of running `./build.sh` here? (make sure to remove any private information beforehand)

(The skeleton folder cannot be launched as it lacks the game files)

**Comment by Lilalou88** [comment]
How can I copy it? In the end it installed a program and it said successfully installed. :( i closed the terminal after so do I have to start from the beginning?

**Comment by Lilalou88** [comment]
Ok, thank you for helping :) this is what it said, so I think something is missing:

_Building DiskSpacePlugin for macOS...
xcode-select: note: No developer tools were found, requesting install.
If developer tools are located at a non-default location on disk, use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, and cancel the installation dialog.
See `man xcode-select` for more details._

**Comment by timkurvers** [comment]
> Building DiskSpacePlugin for macOS... xcode-select: note: No developer tools were found, requesting install.

Ah, this might be something we need to document in the README: to install the tools and re-run the script if necessary.

> user@mbp-user ~ % sh /Users/user/Documents/valheim-macos-main/build.sh Building Valheim > 0.218.15 complete: build/Valheim.app

Did you use the zip-file download to obtain the script?

If so, you may be running into this bit from the README:

> [!IMPORTANT]
>
> Downloading the repository as a zip-file may cause [the build to be damaged](https://github.com/timkurvers/valheim-macos/issues/16#issuecomment-1517025125) due to macOS quarantining files that originate from the internet. Clone the repository instead.

**Comment by Lilalou88** [comment]
Yes I downloaded as a zip file. I don't know how to clone it. I googled it but couldn't find anything. I am so sorry. Can you maybe explain me how to do it? :)

**Comment by timkurvers** [comment]
> Yes I downloaded as a zip file. I don't know how to clone it. I googled it but couldn't find anything. I am so sorry. Can you maybe explain me how to do it? :)

No worries!

First, could you try the following in the root of the `valheim-macos` folder:

> `xattr -cr build`

That may just make it launchable without having to resort to cloning the repository.

**Comment by Lilalou88** [comment]
I don't know how. Do you type these things in the terminal? And I don't find the Valheim folder.. I am sorry but that's the first time I do sth like that...

**Comment by timkurvers** [comment]
> I don't know how. Do you type these things in the terminal? And I don't find the Valheim folder.. I am sorry but that's the first time I do sth like that...

Yes, you run it in the exact same spot where you ran `build.sh` earlier.

**Comment by MrDolphinCodes** [comment]
Not sure if this helps but there is a complete video guide on how to setup the build [here](https://www.youtube.com/watch?v=YPlDY7EjrUU). You might want to restart if you messed up something critical.

**Comment by Lilalou88** [comment]
Ahh thank you so much, I will watch it :) because I don't know how to run a root folder etc... it's really if you haven't done anything like that before, so confusing and I had to google every single step :D will watch it. Thanks for helping guys

**Comment by Lilalou88** [comment]
Cloning is not working because it won't let me put my github password.

**Comment by Lilalou88** [comment]
Hey guys, thanks for your help, it works after all. Do you know by any chance if I had it on a windows before, is it possible to somehow get my character back?

**Comment by MrDolphinCodes** [comment]
Yes it is. You just have to copy over your world and character files. I’m not at my computer right now but I can send some more detailed instructions later.
