### ISSUE TITLE
Encountered 401 for depot manifest 892971 6968333214162889388. Aborting.

### ISSUE THREAD

**Issue by Eucliddd** [timkurvers/valheim-macos#103]
STEAM GUARD! Use the Steam Mobile App to confirm your sign in...
 Done!
Using Steam3 suggested CellID: 198
Got 284 licenses for account!
Got AppInfo for 892970
Using app branch: 'public-test'.
Got depot key for 892971 result: OK
Processing depot 892971
Downloading depot manifest...Got manifest request code for 892971 6968333214162889388 result: 17961670668733972219
Encountered 401 for depot manifest 892971 6968333214162889388. Aborting.

Unable to download manifest 6968333214162889388 for depot 892971
App 892970 was not completely downloaded.
The operation was canceled.
Disconnected from Steam

**Comment by Eucliddd** [comment]
eventually make it run, my solution:
using steamcmd to download valheim app files, copy the valheim_Data folder to vendor/depots/892971/14349377/, then run build.sh

**Comment by timkurvers** [comment]
This looks like firewall / geo-location issues: https://github.com/SteamRE/DepotDownloader/issues/424

Glad you got it solved! 🥳  Will go ahead and close this, feel free to re-open if you run into specific issues with the Valheim build script.
