### ISSUE TITLE
Automatic Updates

### ISSUE THREAD

**Issue by natsukirei** [timkurvers/valheim-macos#13]
Hey team

I noticed my games out of date, but i cant find instructions on updating the client and files to the latest versions automatically.

**Comment by timkurvers** [comment]
Hi! I will be adding instructions to the README for this later this week.

For now:

1. Pull in the latest changes `git pull`
2. Re-run the build-script: `./build.sh`

**Comment by timkurvers** [comment]
More than welcome 😊 Have added a [`Patching`-section](https://github.com/timkurvers/valheim-macos#patching) to the README.
