### ISSUE TITLE
Cracked version support

### ISSUE THREAD

**Issue by Valdex** [timkurvers/valheim-macos#17]
Im not ready to buy this game, but i want try it, how can i download this game for free and build project

**Comment by zenangst** [comment]
You can't.

**Comment by timkurvers** [comment]
The script requires a Steam account that owns Valheim. This is by design as GitHub does [not allow content which bypasses product licensing](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies#3-intellectual-property-authenticity-and-private-information).

**Comment by ezamelczyk** [comment]
Sorry for digging inside closed issues but if anyone stumbles here with this question again I recommend just buying the game and if you're not happy steam always gives refunds if you play less than 2 hours.
