### ISSUE TITLE
Android port ?

### ISSUE THREAD

**Issue by Foul-Tarnished** [timkurvers/valheim-macos#18]
Are you interested in making an unofficial port for Android ?
Hopefully with controller support

SD 8 Gen 1/2 should be powerful enough to run the game decently
(I mean they can run most switch games through Skyline emulator at like 400% speed for some 3D heavy games)

**Comment by timkurvers** [comment]
Hi there! Out of scope for this repository, but here's to hoping Iron Gate will support more platforms in the future 🍻

**Comment by Foul-Tarnished** [comment]
I'm afraid they'll never support Android.
MacOS, probably.
Switch would happen before Android lmao

**Comment by timkurvers** [comment]
Yeah, I am inclined to agree with you there: iOS and Android seem unlikely.
