### ISSUE TITLE
Is it possible to access the console using valheim macros

### ISSUE THREAD

**Issue by DarthCentral** [timkurvers/valheim-macos#20]
Thank you Tim for the valheim macros, it's working well on our 2017 (!) imac. my kid really wants to enable cheats, and so we've tried to activate the console feature, following instructions to add the "-console" to the steam launch options. we can't get it to work.  maybe there's a better forum to ask this question, but thought I'd start here in case any savvy users have figured it out. (i'm the not-so-technically savvy parent ;))

**Comment by timkurvers** [comment]
Hi DarthCentral, great news that it runs well on a 2017 model Mac!

The easiest way is likely launching Valheim from the terminal using `open build/Valheim.app --args -console`.

Alternatively, I've seen reports that adding the game as a non-Steam game allows launching it with the launch arguments specified in Steam. I haven't tried this method myself.

**Comment by timkurvers** [comment]
Closing this issue, feel free to comment/re-open if still not resolved.
