### ISSUE TITLE
Can't download build

### ISSUE THREAD

**Issue by Berezishe** [timkurvers/valheim-macos#22]
Trying to make ./build.sh and have this message:

Warning: Depot 892971 does not have branch named "Public". Trying public branch.
Depot 892971 () missing public subsection or manifest section.
Total downloaded: 0 bytes (0 bytes uncompressed) from 0 depots
Disconnected from Steam
Valheim data not found, exiting..

Could you please help?)

**Comment by timkurvers** [comment]
It seems Steam/Valve have [messed something up](https://github.com/SteamRE/DepotDownloader/issues/428) for certain games, Valheim included.

Thanks for your PR (#23), seems to work well! 🥳 Merged in cf0ad5d2780918cbffea7f0ceeeff22b38b0ecd2.
