### ISSUE TITLE
Stuck On Loading Screen For Multiplayer

### ISSUE THREAD

**Issue by Ghostkwebb** [timkurvers/valheim-macos#24]
I just downloaded Valheim and when I opened it it reached the Valheim logo and then crashed.

Is it because you have to update Valheim for the latest version or something??

**Comment by timkurvers** [comment]
Hi! If you only recently made a build using this script, it should be on the latest 0.215.2 patch. You can verify this by inspecting `Valheim.app` in Finder. It should list a version tag.

Prior to running `Valheim.app`, make sure Steam (the macOS app) is running, you are logged in and the account you are logged into owns Valheim?

If that does not solve it, have a look at `~/Library/Logs/IronGate/Valheim/Player.log` which (at the bottom) may reveal more information why Valheim is crashing.

**Comment by Ghostkwebb** [comment]
Oh I'm dumb thanks I will tell you if I run into any other problems but THANKS!

**Comment by Ghostkwebb** [comment]
So I tried joining my friend and it just keeps loading and idk what to do :(
Sorry to bother

**Comment by Berezishe** [comment]
I have same multiplayer problem. Only singlplayer work well.

**Comment by timkurvers** [comment]
Usually only world generation (_not_ joining an existing world) takes a long time. Does it eventually load? Is there anything of note in `~/Library/Logs/IronGate/Valheim/Player.log`?

**Comment by Ghostkwebb** [comment]
[Player.log](https://github.com/timkurvers/valheim-macos/files/11571912/Player.log)

**Comment by Ghostkwebb** [comment]
idk if u did something but it works now so thanks
