### ISSUE TITLE
Command not found 

### ISSUE THREAD

**Issue by Lajber** [timkurvers/valheim-macos#30]
I have been having issue after typing in the username I get the response "./build.sh: line 61: dotnet: command not found", I downloaded dotnet and tried to find an solution for this but none worked. 
![Screenshot](https://github.com/timkurvers/valheim-macos/assets/136845842/3d142ef3-0471-4839-8f5e-46696223144a)

**Comment by timkurvers** [comment]
Could you try opening a fresh terminal window and executing: `dotnet --version`.

If that prints a version (e.g. `7.0.100`), try running the script again. If it does _not_ print the version, the dotnet install did not succeed.

**Comment by Lajber** [comment]
I used the offical Dotnet installer and it seems that it didn't install properly. I tried the method with Homebrew and it no longer showed that message after entering the username.
