### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by powerdan** [timkurvers/valheim-macos#36]
Hi,

first of all: Thank you for your absolute amazing work! It worked like a charm!

i have build it on the weekend, played a few hours with no problem (and finally dont need geforce now anymore :) )

However: I tried to play another round and the game crashes after the "Valheim" loading screen. I have rebuild it in development mode. See the log here: https://gist.github.com/powerdan/b2be58ca1bd8e1c9d50fd7a2b7b76af1

Best
Daniel

**Comment by timkurvers** [comment]
More than welcome @powerdan!

The log indicates that no active Steam process was found:

> [S_API FAIL] SteamAPI_Init() failed; ipcserver init failed .
> [S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.

This can sometimes happen even when you _do_ have Steam running, perhaps when it marks you as offline or something. Try quitting Steam entirely and opening it up fresh.

**Comment by powerdan** [comment]
d'oh! i checked the log and didnt see that obvious line....

Now it works - thank you!
