### ISSUE TITLE
Build not working (stops before downloading Unity)

### ISSUE THREAD

**Issue by cacadealpaca** [timkurvers/valheim-macos#39]
Hey Tim

I tried build a few times but it always seem to stop at this point: 

Deleted depots/892971/11978864/valheim_Data/StreamingAssets/fonts/default.manifest
Depot 892971 - Downloaded 245170944 bytes (584665212 bytes uncompressed)
Total downloaded: 245170944 bytes (584665212 bytes uncompressed) from 1 depots
Disconnected from Steam
Valheim data for build 11422039 not found, exiting..
(the build script may need to be updated if a patch was recently released) 

Just before it is supposed to ask if I should download Unity and so on. 

Any help much appreciated - very excited to try out this port you made! 

Jack

**Comment by Added-Glue** [comment]
Jack, I'm just another person trying to figure this out and from what I can tell, it looks like you've got a conflicting mix of [build.sh] Valheim version numbers. 11978864 is for [Patch 0.217.14] 11422039 is [Patch 0.216.9]. So it can't compute which version you wan to download and is erroring out at that point. 

I just got it working with the latest patch by following the [README.md] to "1. Clone this repository" using the terminal "git clone" command. Once that was done, I copied the raw text from the latest [build.sh] at:
https://github.com/timkurvers/valheim-macos/tree/feat/patch-0.217.14
Opened the [build.sh] on my local hard drive using a text editor, selected all and pasted the updated version I just copied, saved and closed.
Then I continued using the remaining [README.md] steps and it worked. (Don't forget to have Steam open when you launch the Valheim app.) Thank for making this Tim!

**Comment by cacadealpaca** [comment]
It works now! Thank you so much for your help, just had to copy the build.sh text as you said. 

I seem to be getting extremely good performance on a M1 Pro 14", only had some issues with the cloud sync but eventually managed to get my old world backup to load. 

Thank you to everyone involved for creating this port - I was relying on GeForce Now to stream the game but now I can finally play it directly from my Mac. See you in Valhalla!!!

**Comment by timkurvers** [comment]
Glad you got this sorted! 🥳  The latest patch support is now merged (no need to grab it from the branch).
