### ISSUE TITLE
Doesn't seem to work on MacOS Sonoma

### ISSUE THREAD

**Issue by WhyJAVAidk** [timkurvers/valheim-macos#40]
I know it's a beta OS but I wanted to try if there is any performance differences between Ventura and Sonoma but couldn't get it run on Sonoma. Did a clean install but it is the same the game opens the logo shows but crashes right after. Also tried running on crossover and GPTK but the performance seems very very bad.

**Comment by timkurvers** [comment]
I haven't personally tried it on Sonoma but would expect it to work.

Are you sure Steam is running? There may be more information in the `~/Library/Logs/IronGate/Valheim/Player.log` file.

**Comment by WhyJAVAidk** [comment]
Im running steam in the background and having this terminal output 
<img width="583" alt="Screenshot 2023-09-03 at 11 41 44" src="https://github.com/timkurvers/valheim-macos/assets/32793219/925d16a3-661a-4d1b-842d-db42002bdd3d">

**Comment by WhyJAVAidk** [comment]
Ok I did figure it out if someone who has the same problem as me can do it too. I did a fresh install on unity editor (Unity-2020.3.45f1.pkg) for Mac and it got the game working.

**Comment by timkurvers** [comment]
Judging by the log, the Steam application ID was missing:

> 09/03/2023 11:40:14: Failed to find APPID
> 09/03/2023 11:40:14: Using steam APPID:0
> 09/03/2023 11:40:14: Invalid APPID

This is normally placed automatically into the game package, so not entirely sure where that went wrong.

Glad you got it to work in the end! 🎉

**Comment by geekykayaker** [comment]
I'm seeing the same thing, I've tried running:
`git clean -dfx
./build.sh`

Which should reinstall everything right?
Or did you download the package from the Unity website and install manaully?

**Comment by timkurvers** [comment]
I wonder if Unity extraction can fail under some very specific circumstances.

Could you try renaming `vendor/Unity-2020.3.45f1` to something else and then re-run the script. It should re-extract the files. If you suspect the Unity download to be corrupt, try renaming the `.pkg` file, too.

**Comment by geekykayaker** [comment]
The git clean wipes the whole folder out, so I would have thought that would be enough?

**Comment by timkurvers** [comment]
Ah right, sorry, did not register the flags passed to `git clean`.

Is there anything of interest in the build script output? Errors from `pkgutil` or otherwise?

**Comment by geekykayaker** [comment]
Not that I've noticed. I've just re-kicked the install, so I'll keep an eye out.

**Comment by geekykayaker** [comment]
Hmmm... Nothing out of ordinary in log at all.

**Comment by timkurvers** [comment]
If the game is erroring out with `Invalid APPID`, could you check `build/Valheim.app/Contents/Info.plist` whether SteamAppId is correctly in there?

**Comment by timkurvers** [comment]
Hm, curious indeed. Anything interesting in extended attributes on the app itself, or the executable?

```shell
xattr build/Valheim.app
xattr build/Valheim.app/Contents/MacOS/Valheim
```

**Comment by geekykayaker** [comment]
Hmmm, nothing for either of those...

**Comment by timkurvers** [comment]
Could you try executing the binary directly as follows:

```
./build/Valheim.app/Contents/MacOS/Valheim -logfile /dev/stdout
```

I doubt the game will launch properly (Steam will likely fail to initialize) but worth a shot to see whether macOS is preventing it from launching, and what type of log output you may get.

**Comment by geekykayaker** [comment]
Ok, so the game launches the same as it does without the logfile option, and quits at the same point.

This is the first error I get

```
NullReferenceException: The WorldGenerator instance was null
  at Heightmap.Generate () [0x0001a] in <515edd01a8ff4d22b13da559af22489c>:0 
  at Heightmap.Regenerate () [0x00007] in <515edd01a8ff4d22b13da559af22489c>:0 
  at Heightmap.OnEnable () [0x00029] in <515edd01a8ff4d22b13da559af22489c>:0 
```

Then I get some of these:

```
NullReferenceException: Object reference not set to an instance of an object
  at Localization.GetBoundKeyString (System.String bindingName, System.Boolean emptyStringOnMissing) [0x00005] in <1cc5e200d8fe4d129ecc905a7d16b102>:0 
  at Localization.Translate (System.String word) [0x0003a] in <1cc5e200d8fe4d129ecc905a7d16b102>:0 
  at Localization.Localize (System.String text) [0x0001e] in <1cc5e200d8fe4d129ecc905a7d16b102>:0 
  at Localization.Localize (UnityEngine.Transform root) [0x00024] in <1cc5e200d8fe4d129ecc905a7d16b102>:0 
  at Localize.Start () [0x0000b] in <1cc5e200d8fe4d129ecc905a7d16b102>:0 
```

**Comment by timkurvers** [comment]
Can you double-check that Steam is running (the macOS client) and you are signed in with an account that owns Valheim?

**Comment by geekykayaker** [comment]
Damn, is this whole thing because I've not been running Steam...
I'm sure I've tried it with Steam before.
Hang on

**Comment by geekykayaker** [comment]
Oh FFS, it's fine now, sorry for the huge waste of time.
I think the original issue must have been some problem with stale files, and I just hadn't realised I was no longer running steam in the background when I did the git clean....

**Comment by timkurvers** [comment]
No worries, glad it's working 🥳 

I'll go ahead and close this issue, but if either of you were to encounter any Sonoma specific issues, please reply or open an issue 🙏

**Comment by geekykayaker** [comment]
Thanks so much, appreciate all the help!
