### ISSUE TITLE
I can't download

### ISSUE THREAD

**Issue by Dm1tryRin** [timkurvers/valheim-macos#47]
I can't download. Everything worked before the update. I couldn't update - I decided to reinstall again.

Last terminal lines:

Depot 892971 - Downloaded 897734032 bytes (1544312342 bytes uncompressed)
Total downloaded: 897734032 bytes (1544312342 bytes uncompressed) from 1 depots
Got 133 licenses for account!
Disconnected from Steam
Valheim data for build 12314274 not found, exiting..
(the build script may need to be updated if a patch was recently released)

Please help.

**Comment by Dm1tryRin** [comment]
I'm sorry - I didn't see that a new version 0.217.24 was released

**Comment by timkurvers** [comment]
Have documented the build-failure as a known issue in the README: 39270c14bb9ce6f6f338c877027023aedebbdaf8.

#46 is now merged so building `0.217.24` should work now on the `main`-branch 🥳
