### ISSUE TITLE
Action and attack input get stuck

### ISSUE THREAD

**Issue by razvanilin** [timkurvers/valheim-macos#48]
Not sure if this is related to my peripherals (magic keyboard and MX master 3s), but whenever I do an activity in quick succession, the actions feel like they get in a queue of some sorts and it's impossible to stop. Some examples:

- The worst one by far - Attacking. If I get into a fight and press the attack button quickly, the character gets stuck attacking exactly how many times I pressed the attack button and cannot stop it. Sometimes attacking even gets stuck completely and I have to press attack button again to stop it (RIP stamina + died so many times because of this).
- Another clear one is repairing equipment. On Windows I was smashing the repair button quickly, but on Mac everything gets stuck for a couple of seconds when I do that.

Anyone else encountered this before? I wonder if it has something to do with how input is handled on MacOS

**Comment by timkurvers** [comment]
I briefly tested this last night on regular laptop setup (keyboard/trackpad) and could not reproduce this in 0.215.24 (latest stable)

Did this start happening recently or has it always been like this for you? Is there anything of note in the log files?

**Comment by stvnksslr** [comment]
@razvanilin are you using a tiling manager like rectangle or magnet? they tend to interact badly with games like this. I was slowly going mad with the same issue until i added valheim to the exclusion list.

**Comment by razvanilin** [comment]
@stvnksslr omg that's it! I was using magnet and I just tried closing it. Works super nicely now 👌 

I'll close this as it doesn't seem to be related to the game
