### ISSUE TITLE
Instant crash after newest patch

### ISSUE THREAD

**Issue by andnischneider** [timkurvers/valheim-macos#67]
Hi,

I've been playing a lot with this port up until maybe 3 or 4 patches ago. Now I hadn't played a while and wanted to update, so I pulled, deleted the contents of the "vendor" folder and ran the build.sh script to download everything again. My terminal says that 0.217.31 was installed successfully, but the game crashes instantly without even starting up when I want to open it.

I'm running Sonoma 14.1.1 on an M1 Pro.

Would it be of any help to attach the Mac OS crash report? It says that the "crashed thread" is called "2 AssetGarbageCollector"

Thanks!

**Comment by timkurvers** [comment]
That's unfortunate, is this still happening?

There may be something of use in the `Player.log` file, located in your local user's library folder: `~/Library/Logs/IronGate/Valheim/Player.log`.

**Comment by andnischneider** [comment]
Yes, I tried reinstalling it and it keeps happening, unfortunately. Now I don't seem to get the Mac crash report anymore though for some reason. Pasting the contents of the Player.log file below, there seems to be a file missing:

> Mono path[0] = '/Users/ansr0007/Documents/Vh/valheim-macos/build/Valheim.app/Contents/Resources/Data/Managed'
Mono config path = '/Users/ansr0007/Documents/Vh/valheim-macos/build/Valheim.app/Contents/MonoBleedingEdge/etc'
The assembly mscorlib.dll was not found or could not be loaded.
It should have been installed in the `/Users/ansr0007/Documents/Vh/valheim-macos/build/Valheim.app/Contents/Resources/Data/Managed/mono/4.5/mscorlib.dll' directory.
