### ISSUE TITLE
A couple of tiny suggestions (and a big thanks!)

### ISSUE THREAD

**Issue by nathanlesage** [timkurvers/valheim-macos#80]
Hey,

First of all: thank you so much for making this work. I have a windows desktop but I am frequently on the road for which I only have a MacBook, and this repository with your work is a godsend for being able to play Valheim while not at home. I gave it a try yesterday and it all worked flawlessly!

If you want to add another performance spec to the list in the Readme: I have a 14'' MBP M2 Pro with 16GB of memory, and I achieved ca. 30-50 fps on 2k resolution and 50-70 fps on 1080p with all graphics settings maxed out, so it really worked well.

I have two very minor suggestions to improve the build script: First, I really appreciate the transparency as to what will be downloaded, but I feel that it might make the script more ergonomic if you would ask for a collective yes for all downloads -- the thing is, if we want to build the macOS Valheim app, we will need all of the packages, and it felt a bit tedious having to say yes four or five times in a row. It is definitely not a show stopper, but I feel it might make the whole experience more ergonomic.

Then, you mention that we need a steam account that owns Valheim, but I was a bit surprised (even though it was really to be expected) that I have to provide username and password for my steam account. Since I normally only log in to my steam account once when I install it on a new computer I had the pleasure of having to restart the script ten times because I forgot my credentials 🙈 I think adding a note that one will have to log in might make it less painful for people because one can collect all info beforehand and then run through everything!

As I said, these are only two minor suggestions and should not cast a shadow on this amazing work, thank you again!

**Comment by timkurvers** [comment]
Thanks! Agreed on both bits. Bit swamped with other things, but will keep this open for future fixing.

**Comment by OO00O0O** [comment]
I just wanted to leave "Thank you" message too. It's just amazing that this works so great on my(work;) M1. I was really craving this gave, after my GTX 970 went down.

Thank you!

**Comment by genghisjahn** [comment]
This is great work. I play only on my MBP with no issues.

**Comment by timkurvers** [comment]
Closing this issue as the official macOS client is now available! 🥳 (see #104)
