### ISSUE TITLE
App crashes immediately

### ISSUE THREAD

**Issue by luke-m** [timkurvers/valheim-macos#90]
Hey, I just stumbled upon your project and wanted to give it a go. I tried building the main branch but that seems to be outdated because of a patch. Then I saw that there's a branch `` for the new patch so I tried building that. The build finished successfully but when I try to open the application, nothing happens. I checked the `Player.log` file and it contains this:

```
Mono path[0] = '/Users/*/Documents/dev/valheim-macos/build/Valheim.app/Contents/Resources/Data/Managed'
Mono config path = '/Users/*/Documents/dev/valheim-macos/build/Valheim.app/Contents/MonoBleedingEdge/etc'
[Physics::Module] Initialized MultithreadedJobDispatcher with 7 workers.
Invalid serialized file version. File: "/Users/*/Documents/dev/valheim-macos/build/Valheim.app/Contents/Resources/Data/globalgamemanagers". Expected version: 2022.3.17f1. Actual version: 2022.3.12f1.
Unknown error occurred while loading '/Users/*/Documents/dev/valheim-macos/build/Valheim.app/Contents/Resources/Data/globalgamemanagers'.
PlayerInitEngineNoGraphics settings: Failed to load PlayerSettings (internal index #0).
Most likely data file is corrupted, or built with mismatching
editor and platform support versions.
Failed to initialize engine
```

I'm using an M1 Pro with macOS 14.4.1.

**Comment by luke-m** [comment]
OK I just retried with building from the main branch with the --beta flag and it works. I'll close this issue. Thanks for your work!

**Comment by timkurvers** [comment]
Excellent! 🥳 Just merged the PR into the main branch. The build seems to work fine locally for me. If you happen to run into a similar issue in the future, please re-open 🙏
