### ISSUE TITLE
Console Inaccessible

### ISSUE THREAD

**Issue by tojala1998** [timkurvers/valheim-macos#91]
I seem to be unable to access the game's console, the F2 menu works just fine but F5 won't bring up the console at all.

I've tried launching through steam with launch options, and through terminal with the same launch options. I've tried remapping F5 to my mouse 5 button thinking it's a keyboard issue, but that fails as well. I'm running the game with BetInEx and 16 plugins, but I've tested this vanilla as well, and with a fresh install following the guide.

Any thoughts?

**Comment by drummercraig** [comment]
The only way I was able to get the console is to use the ServerDevcommands mod from JereKuusela. Do you have that one installed?

**Comment by tojala1998** [comment]
@drummercraig I do have ServerDevcommands, updated, however I still can't open the console.

**Comment by drummercraig** [comment]
Are you launching from steam or terminal? I could not make it work with steam launch.


On Apr 18, 2024, at 3:53 PM, tojala1998 ***@***.***> wrote:

﻿

@drummercraig<https://github.com/drummercraig> I do have ServerDevcommands, updated, however I still can't open the console.

**Comment by drummercraig** [comment]
Also, do you see the Bepinex info in the top left at the main screen? Does it say right there to press F5 for the console?

**Comment by tojala1998** [comment]
I've tried steam and the terminal, and yes BepInEx does indicate "Press F5 for Console" in the corner. It doesn't work in-game, in the menu, or even when remapped off the keyboard. I also tested it in a different user profile just to be safe, wondering if mac keyboard shortcut settings were causing the issue.

**Comment by MrDolphinCodes** [comment]
I just saw this but in case you haven't already figured it out you have to start valheim by running this command in your console `open /users/math/valheim-macos/build/Valheim.app --args -console` (this is assuming your valheim.app is still in your build folder if not you will need to modify the path). This solution is also in FAQ section of the README.

**Comment by tojala1998** [comment]
@MrDolphinCodes yeah that doesn't allow me to open the console

**Comment by MrDolphinCodes** [comment]
@tojala1998 Are you trying on single player or multiplayer?

**Comment by tojala1998** [comment]
> @tojala1998 Are you trying on single player or multiplayer?

I tried on single player.

**Comment by MrDolphinCodes** [comment]
Weird, this has worked for me on all of my mac devices. The only thing I can think of is are you sure you are pressing the `fn` and `F5` key at the same time?

**Comment by Gijeeg86** [comment]
Any solution found? With the native app bought on App Store I have same issue. I created a script to launch with "-console" arg but in-game F5 key does nothing (and the key is working outside the game).

**Comment by genghisjahn** [comment]
Just hit enter. The official build didn't recognize f5 for me. But hitting enter did.

**Comment by Gijeeg86** [comment]
Hitting enter opens the chat and the only command recognized is /devcommands. Other than that no command is recognized, such as debugmode or other cheat commands

**Comment by drummercraig** [comment]
Have you tried a different keyboard? I happen to be using a Logitech from a PC. My System Settings - Keyboard shows Press fn key to "Do Nothing", Input Sources is U.S.

Also, my Privacy & Security - Input Monitoring allows Steam and Valheim.

**Comment by tojala1998** [comment]
> Have you tried a different keyboard? I happen to be using a Logitech from a PC. My System Settings - Keyboard shows Press fn key to "Do Nothing", Input Sources is U.S.
> 
> Also, my Privacy & Security - Input Monitoring allows Steam and Valheim.

I haven't but I suspect this will have something to do with it. I haven't done any testing since they released valheim on mac... Hoping overwolf will be released on mac and we can use thunderstore

**Comment by timkurvers** [comment]
Closing this issue as the official macOS client is now available! 🥳 (see #104)

---

Recommend getting in touch with Valheim support if this issue still persists on the official version. There's also a `#mac-bugs-discussion` channel on the official Valheim Discord.
